GET HTTP://localhost:3000/products


###
GET HTTP://localhost:3000/products/1


###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Shinguards",
  "price": 20,
  "description": "Protection for your shins. Required by refs everywhere.. unfortunately"
}