#just for testing locally. Front end replaces entirely. 

GET HTTP://localhost:3000/products.json


###
GET HTTP://localhost:3000/products/22.json


###
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "Shinguards_1",
  "price": 20,
  "image_url": "test_url",
  "description": "Protection for your shins. Required by refs everywhere.. unfortunately",
  "supplier_id": 2
}


###
PATCH http://localhost:3000/products/16.json
Content-Type: application/json

{
  "name": "Shinguards_1",
  "price": 20,
  "image_url": "test_url",
  "description": "Protection for your shins. Required by refs everywhere.. unfortunately"
}


###
DELETE http://localhost:3000/supplier/1.json

# PRODUCTS

###
GET HTTP://localhost:3000/suppliers.json


###
GET HTTP://localhost:3000/suppliers/2.json


###
POST http://localhost:3000/suppliers.json
Content-Type: application/json

{
  "name": "",
  "email": "",
  "phone_number": "234"
}


###
PATCH http://localhost:3000/suppliers/4.json
Content-Type: application/json

{
  "name": "Puma",
  "email": "puma@puma.com",
  "phone_number": "1092834756"
}


###
DELETE http://localhost:3000/suppliers/3.json


###
# User Add Image:
post http://localhost:3000/images.json
Content-Type: application/json

{
  "url": "",
  "product_id": ""
}

### Sign up (create new user)
post http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Bill",
  "email": "bill@bill.com",
  "password": "password",
  "password_confirmation": "password" 
}

### Generate jwt (sign in)
post http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test_email",
  "password": "password"
}

###test active session
GET HTTP://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NjAwNjM0MjF9.oTWYmNJolUcwSTGH2BMchSn661Tjq1WzSH4KfAP3y0Y


### Create order
post http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NjAwNzE3MzR9.bSHSP0lm_qTSxTxrIHIV35MXjzoFlA8tf_LOlcLpdMY
Content-Type: application/json

{
  "product_id": 11,
  "quantity": 2
}


### Orders Index
get http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NjAwNzE3MzR9.bSHSP0lm_qTSxTxrIHIV35MXjzoFlA8tf_LOlcLpdMY


### Orders Show
get http://localhost:3000/orders/2.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjAwNzMwNTZ9.A4L6R7dQWOHYETyAR7Tqf-bGaybtwUq8wUHV2q-etHU
