#just for testing locally. Front end replaces entirely. 

GET HTTP://localhost:3000/products


###
GET HTTP://localhost:3000/products/3


###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Shinguards",
  "price": 20,
  "image_url": "test_url",
  "description": "Protection for your shins. Required by refs everywhere.. unfortunately"
}


###
PATCH http://localhost:3000/products/7
Content-Type: application/json

{
  "name": "Shinguards",
  "price": 20,
  "image_url": "test_url",
  "description": "Protection for your shins. Required by refs everywhere.. unfortunately"
}


###
DELETE http://localhost:3000/products/17